### ISSUE TITLE
Better UX in Timings module

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/amrita-repository#10]
**Is your feature request related to a problem? Please describe.**
- Currently the app merely lists the timings which is a humongous task to search through.

**Describe the solution you'd like**
- A nice UX update would be to highlight the next bus/train time by checking current time.

**Comment by ArunVigesh** [comment]
Will do IT

**Comment by rajkumaar23** [comment]
### Also, add a back button to these activities : 
![image](https://user-images.githubusercontent.com/37476886/77228989-17bf0700-6bb1-11ea-889c-bebe37c1af48.png)

**Comment by ArunVigesh** [comment]
Okay
