### ISSUE TITLE
Save incoming notifications 

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/amrita-repository#15]
**Is your feature request related to a problem? Please describe.**
Whenever there is a notification, as soon as we click on that, it disappears. 

**Describe the solution you'd like**
- So we need a notifications activity that saves all the incoming notifications in a local [Room](https://developer.android.com/topic/libraries/architecture/room)  database.
- When the notification is clicked, it should take an activity that displays only that particular notification details.
- Additionally, in the list view of notifications, autolink for any websites should be enabled so whenever there’s a website embedded in the notification text, it should be clickable.
- Note that, the notification will have a title & body.

**Comment by thelordtech** [comment]
Senjuta pochu!!!
