### ISSUE TITLE
AUMS access issues

### ISSUE THREAD

**Issue by italiyak1** [rajkumaar23/amrita-repository#54]
**Describe the bug**
The application crashes as we try to access the AUMS after installing the latest updates

**To Reproduce**
1. Open the application.
2. Click on the AUMS tab to access it.
3. The application crashes immediately.

**Expected behavior**
Access of AUMS with the features of attendance, marks, grades, and resources ( as mentioned in the update)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Android Studio Version

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J7 nxt
 - OS: One UI

**Additional context**

**Comment by rajkumaar23** [comment]
@italiyak1 I'm aware of the issue. Some weird bug due to encryption. Will be rolling out an update by tonight.
