### ISSUE TITLE
Exam Schedule not rendered properly

### ISSUE THREAD

**Issue by capturemathan** [rajkumaar23/amrita-repository#56]
**Describe the bug**
1. The title of the Exam Schedules is missing.
2. Upon clicking any one of the entries, the app crashes.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/36666781/82730865-89860f00-9d20-11ea-9214-d73d66e7cf54.png)

**Comment by rajkumaar23** [comment]
They changed the whole page 😭

**Comment by capturemathan** [comment]
> They changed the whole page 😭

Lol just letting you know 😄

**Comment by rajkumaar23** [comment]
@capturemathan 
The issue is fixed. You can verify and close this issue.

**Comment by capturemathan** [comment]
> @capturemathan
> The issue is fixed. You can verify and close this issue.

It's working fine bruh
