### ISSUE TITLE
Make use of in-app-updates API

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/amrita-repository#57]
Ref : https://developer.android.com/guide/playcore/in-app-updates

**Comment by yogesh5466** [comment]
I Will work on this. 
In-app updates work only with devices running Android 5.0 (API level 21) or higher
is it ok to change minSdkVersion=21 ?

**Comment by rajkumaar23** [comment]
> I will work on this. 
> 
> In-app updates work only with devices running Android 5.0 (API level 21) or higher
> 
> is it ok to change minSdkVersion=21 ?

Yes, please go ahead. There are only 0.002% devices running < 21. We can ignore them.

**Comment by yogesh5466** [comment]
ok

**Comment by yogesh5466** [comment]
Testing this won’t work on a debug build.
You would need a release build signed with the same key you use to sign your app before uploading it to the Play Store. It would be a good time to use the internal testing track.
@rajkumaar23

**Comment by rajkumaar23** [comment]
Yes, I’ll take care of that. 👍🏼
