### ISSUE TITLE
Hardcoded Department Names

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/amrita-repository#9]
**Describe the bug**
- The department names are hardcoded in QPapers module as well as Academic Timetable.

**Expected behavior**
- For QPapers, fetch the departments from **DSpace** website and update in SharedPrefs and fetch it when required.
- For Academic Timetable, get the course and department dynamically from [here](https://intranet.cb.amrita.edu/TimeTable/)

**Comment by sanjailal** [comment]
I am working on it

**Comment by rajkumaar23** [comment]
@sanjailal Raise a PR after fixing the hardcoded depts in QPapers module 😉
